### ISSUE TITLE
Actions suddenly failing until github cancels run

### ISSUE THREAD

**Issue by ryanseddon** [ianwalter/puppeteer-container#111]
I've had a few actions that run on schedule twice a day that use this action and it has worked fine for months only recently this action started hanging and not completing its task and just timing out, I didn't set a timeout on these jobs and they hung for the default 360 minutes.

The actions I have are private so I cant share the runs but the action file is running this:
```yml
      - name: Generate stats
        env:
          API_KEY: ${{ secrets.G_TOKEN }}
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm run stats
```

Where `npm run stats` is just running `node index.js` that loads up puppeteer, again this job has been running fine for months with no changes and now it's failing? I'm wondering if a change in github has effected this? Has anyone else had this problem?

This is the log from the action run itself:

```bash
Run ianwalter/puppeteer-container@v4.0.0
  with:
    args: npm run stats
  env:
    API_KEY: ***
/usr/bin/docker run --name [hash] --label [hash] --workdir /github/workspace --rm -e API_KEY -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/repo_name/repo_name":"/github/workspace" [hash]:[hash] npm run stats

> repo_name@1.0.0 stats /github/workspace
> node index.js

Error: The operation was canceled.
```

**Comment by facutk** [comment]
Had the same issue, and had to switch to https://github.com/ianwalter/playwright-container

**Comment by ianwalter** [comment]
Hey, sorry, missed this issue. I'll take a look.

**Comment by facutk** [comment]
Thanks @ianwalter ! Hopefully it's something easy to catch!

**Comment by alexanderdavide** [comment]
Sadly, this issue still exists. Therefor I switched to [puppeteer-headful](https://github.com/alexanderdavide/puppeteer-headful).

**Comment by heddn** [comment]
Still seeing this using `main` HEAD branch. On local, the execution of npm runs just fine. On Github, it just times out.

**Comment by ianwalter** [comment]
I'm not sure what's happening here. I've switched to Playwright and haven't actually used Puppeteer in a while. I'm going to close this since I'm going to deprecate puppeteer-container. I would suggest switching to https://github.com/ianwalter/playwright-container and setting `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` and `PUPPETEER_EXECUTABLE_PATH=/opt/playwright-browsers/chromium-857950` in your CI since that seems to have worked for others.
